language: java


jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "mafeozik"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn verify sonar:sonar \
    -Dsonar.projectKey=mafeozik_sonar-demo \
    -Dsonar.coverage.jacoco.xmlReportPaths=\
     target/site/jacoco/jacoco.xml

after_success:
  - mvn coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
